name: Update My Repos

on: workflow_dispatch

jobs:
  my_repos:
    runs-on: ubuntu-latest
    name: It should do something
    steps:
      - name: My Repos
        id: my-repos
        uses: SubZtep/my-repos-action@main
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
      - name: Let's README
        run: echo ${{ steps.my-repos.outputs.table }}
