name: My Repos

on: workflow_dispatch

jobs:
  my_repos:
    runs-on: ubuntu-latest
    name: Update Profile
    steps:
      - uses: SubZtep/my-repos-action@main
        id: my-repos
        with:
          #token: ${{ secrets.GH_ACCESS_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2
        run: |
          cat ME.md > README.md
          printf "%s" "${{ steps.my-repos.outputs.table }}" >> README.md
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
