name: My Repos

on: workflow_dispatch

jobs:
  my_repos:
    runs-on: ubuntu-latest
    name: Update Profile
    steps:
      - name: Graph Query
        id: my-repos
        uses: SubZtep/my-repos-action@main
        with:
          #token: ${{ secrets.GH_ACCESS_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Refresh Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Compose README
        shell: bash
        run: |
          cat ME.md > README.md
          printf "%s" "${{ steps.my-repos.outputs.table }}" >> README.md
          cat README.md

      - name: Commit Changes
        uses: actions/checkout@v2
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
