name: My Repos

on: workflow_dispatch

jobs:
  my_repos:
    runs-on: ubuntu-latest
    name: Update Profile
    steps:
      - uses: SubZtep/my-repos-action@main
        id: my-repos
        with:
          ago: https://time-passing.netlify.app/.netlify/functions/ago?time=
          token: ${{ secrets.GITHUB_TOKEN }}
          actor: $GITHUB_ACTOR

      - uses: actions/checkout@v2
      - run: |
          cat ME.md > README.md
          printf "%s" "${{ steps.my-repos.outputs.md }}" >> README.md
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -m "generated" -a
          git push
