name: Update My Repos

on: workflow_dispatch

jobs:
  my_repos:
    runs-on: ubuntu-latest
    name: It should do something
    steps:
      - name: My Repos
        id: my-repos
        uses: SubZtep/my-repos-action@main
        with:
          # token: ${{ secrets.GH_ACCESS_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
        run: |
          cat READI.md > README.md
          echo ${{ steps.my-repos.outputs.table }} >> README.md
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
