name: Update My Repos

on: workflow_dispatch

jobs:
  my_repos:
    runs-on: ubuntu-latest
    name: It should do something
    steps:
      - run: echo env
      - uses: SubZtep/my-repos-action@main
        with:
          url: GITHUB_GRAPHQL_URL
          #url: https://api.github.com/graphql
          token: ${{secrets.GH_ACCESS_TOKEN}}
          login: SubZtep
