name: Update My Repos

on: workflow_dispatch

jobs:
  my_repos:
    runs-on: ubuntu-latest
    name: It should do something
    steps:
      - uses: SubZtep/my-repos-action@v0.2.4
        with:
          url: $GITHUB_GRAPHQL_URL
          token: ${{secrets.GH_ACCESS_TOKEN}}
          login: SubZtep
